spring:
  application:
    name: eureka server
server:
  port: 8003
eureka:
  instance:
    hostname: eurekaC
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaB:8002/eureka/,http://eurekaA:8001/eureka/